---

- hosts: all
#  vars_files: 
#    - vault
#    - vars.yml
  tasks:
    - name: Create deployment
      kubernetes.core:
        path: /root/.homeassistant
        state: directory
        mode: '0755'

...